; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:office-modbus]
platform = espressif32
board = esp32s3usbotg
framework = arduino
build_flags = 
  -DWIFI_MANAGER_DEBUG
  -DSENSOR_BACKEND_MODBUS
lib_deps = 
  4-20ma/ModbusMaster@^2.0.1
  knolleary/PubSubClient@^2.8
board_build.filesystem = littlefs
monitor_speed = 115200

[env:home-dht11]
platform = espressif32
board = esp32s3usbotg
framework = arduino
build_flags =
  -DWIFI_MANAGER_DEBUG
  -DSENSOR_BACKEND_DHT11
lib_deps =
  knolleary/PubSubClient@^2.8
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.15
board_build.filesystem = littlefs
monitor_speed = 115200

[env:esp32s3usbotg]
extends = env:office-modbus

[system]
flash_size = 4MB
flash_freq = 80
flash_mode = qio
sdkcomponent = 
  c_stdlib
  c_libc
  newlib
  gcc
  esp32s3_default
build_unflags = 
  -DARDUINO_ARCH_ESP8266